rocketmq:
  # namesrv地址，多个用分号隔开 127.0.0.1:9876;127.0.0.2:9876
  name-server: 127.0.0.1:9876
  producer:
    # 同步发送失败重试次数，默认2，总共 1+2=3次发送
    retry-times-when-send-failed: 2
    # 异步发送失败重试次数，默认2
    retry-times-when-send-async-failed: 2
    # 失败后尽量换一个broker发送，建议true，规避单节点故障
    retry-another-broker-when-not-store-ok: true
    # 生产者分组，必须指定
    group: default-producer-group
    # 发送超时，单位毫秒
    send-message-timeout: 3000
  consumer:
    # 消费最大重试次数，默认16
    max-reconsume-times: 3